"""Phase 4 vault cleanup — cross-category misfiling corrections.

Moves files that are currently in `2.OUTPUT/People/{Network,Reference}/`
but are actually about concepts, companies, media, books, or places.

Move list was generated by an Explore research agent scanning each file's
content and frontmatter. Borderline cases (ancient writers, ambiguous names)
are INTENTIONALLY excluded — they stay in People until user flags them.

Obsidian wikilinks resolve by stem name across the whole vault, so moving
a file does NOT break `[[stem]]` links as long as stems stay unique.
We verify that before every move.

Usage:
  python scripts/vault_cleanup_phase4.py            # dry-run
  python scripts/vault_cleanup_phase4.py --apply    # apply for real
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import shutil
import sys
import tarfile
from dataclasses import dataclass
from pathlib import Path


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

VAULT_ROOT = Path("/Users/cdiseetheeye/Documents/Obsidian_sinc")

# Destination folders (created if missing).
TERM_DIR = VAULT_ROOT / "1.INPUT" / "Term"
MEDIA_DIR = VAULT_ROOT / "1.INPUT" / "Media"
BOOK_DIR = VAULT_ROOT / "1.INPUT" / "Book"
PLACES_DIR = VAULT_ROOT / "2.OUTPUT" / "Wiki" / "Places"

BACKUP_DIR = Path.home() / ".onlime" / "backups"

# Source folders
NETWORK = VAULT_ROOT / "2.OUTPUT" / "People" / "Network"
REFERENCE = VAULT_ROOT / "2.OUTPUT" / "People" / "Reference"


@dataclass
class Move:
    src_rel: str  # relative to VAULT_ROOT, e.g. "2.OUTPUT/People/Network/거울.md"
    dest_dir: Path
    category: str


def _n(name: str) -> Move:
    return Move(src_rel=f"2.OUTPUT/People/Network/{name}", dest_dir=TERM_DIR, category="CONCEPT")


def _r(name: str) -> Move:
    return Move(src_rel=f"2.OUTPUT/People/Reference/{name}", dest_dir=TERM_DIR, category="CONCEPT")


# --------- move list (from Phase 4 research agent, 2026-04-06) ---------

# Concepts → 1.INPUT/Term/
CONCEPT_NETWORK = [
    "갈치뼈.md", "거울.md", "결정.md", "관점.md", "광물학.md",
    "교류분석.md", "기술.md", "기저함수.md", "기준치.md", "껍데기.md",
    "담론.md", "댓글.md", "능력주의.md", "상관관계.md",
    "서사.md", "세로토닌.md", "성공팔이.md", "슬픔.md", "스키마.md",
    "아름다움.md", "야경국가.md", "악수.md", "웃음.md", "자아.md",
    "질문.md", "취향.md", "한계효용.md", "통계역학.md", "통제.md",
    "변호사.md", "학계.md", "스포츠.md", "복지.md", "숏폼.md",
    "버릇.md", "별자리.md", "생일.md", "첫눈.md", "바람.md",
    "엄산마루.md", "무제.md", "미터.md", "현재.md", "신경전달물질.md",
    "해마.md", "의자.md", "심장.md", "키값.md", "청약통장.md",
    "프로.md", "손해배상.md",
]

# Ancient Chinese classics → 1.INPUT/Book/
BOOK_CLASSICS = [
    ("논어.md", NETWORK),
    ("손자병법.md", NETWORK),
]

# Companies / products / tools → 1.INPUT/Term/
COMPANY_NETWORK = [
    "팔란티어_2024 AIP.md", "블록체인_디지털사회와 법.md",
    "타입드_생산성 SaaS 회사.md", "테슬라_옵티머스봇.md",
    "링크드인.md", "넷플릭스.md", "메타.md", "리니지.md",
    "릴스.md", "믹스패널.md", "옵시디언.md", "뉴웨이즈.md",
    "지주회사.md", "브랜드.md",
]

# Media (films, TV, YouTube) → 1.INPUT/Media/
MEDIA_NETWORK = [
    "월터 미티.md", "빅뱅이론_시트콤.md", "루페우스_유튜브.md",
    "안홍신_프리윌링.md", "크라운_롤.md", "뉴욕털게_결심없는 삶.md",
    "괴물(고레에다 히로카츠)_영화.md",
    # OTHER category, clearly media:
    "페니_빅뱅이론.md",
    "시대예보_호명사회(송길영).md",
    "시대예보(송길영).md",
]

# Books → 1.INPUT/Book/
BOOK_NETWORK = [
    "웃음(베르나르 베르베르).md",
    "이키가이(켄 모기).md",
    "나무(B.W.).md",
    "머니볼(M.L.).md",
    "대화록(에픽테토스).md",
    "멕베스.md",
]

# Places → 2.OUTPUT/Wiki/Places/
PLACES_NETWORK = [
    "미국.md",
    "미국_47대 대통령 선거.md",
]

# OTHER (clearly non-person) → 1.INPUT/Term/
OTHER_TERM_NETWORK = [
    "통일교.md",  # religious movement
    "프로메테우스.md",  # mythological concept
]

# OTHER — fictional character in Reference
OTHER_MEDIA_REFERENCE = [
    "바이러스 교수_ 세얼간이.md",
]


def build_moves() -> list[Move]:
    moves: list[Move] = []
    for name in CONCEPT_NETWORK:
        moves.append(Move(f"2.OUTPUT/People/Network/{name}", TERM_DIR, "CONCEPT"))
    for name, src_root in BOOK_CLASSICS:
        src_rel = f"{src_root.relative_to(VAULT_ROOT)}/{name}"
        moves.append(Move(src_rel, BOOK_DIR, "BOOK(classic)"))
    for name in COMPANY_NETWORK:
        moves.append(Move(f"2.OUTPUT/People/Network/{name}", TERM_DIR, "COMPANY"))
    for name in MEDIA_NETWORK:
        moves.append(Move(f"2.OUTPUT/People/Network/{name}", MEDIA_DIR, "MEDIA"))
    for name in BOOK_NETWORK:
        moves.append(Move(f"2.OUTPUT/People/Network/{name}", BOOK_DIR, "BOOK"))
    for name in PLACES_NETWORK:
        moves.append(Move(f"2.OUTPUT/People/Network/{name}", PLACES_DIR, "PLACE"))
    for name in OTHER_TERM_NETWORK:
        moves.append(Move(f"2.OUTPUT/People/Network/{name}", TERM_DIR, "OTHER→TERM"))
    for name in OTHER_MEDIA_REFERENCE:
        moves.append(Move(f"2.OUTPUT/People/Reference/{name}", MEDIA_DIR, "OTHER→MEDIA"))
    return moves


def _unique_dest(dest_dir: Path, filename: str) -> Path:
    dest = dest_dir / filename
    if not dest.exists():
        return dest
    stem = dest.stem
    ext = dest.suffix
    i = 2
    while True:
        cand = dest_dir / f"{stem} ({i}){ext}"
        if not cand.exists():
            return cand
        i += 1


def make_backup(moves: list[Move]) -> Path:
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    ts = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    out = BACKUP_DIR / f"vault-phase4-{ts}.tar.gz"
    with tarfile.open(out, "w:gz") as tar:
        for m in moves:
            src = VAULT_ROOT / m.src_rel
            if src.exists():
                tar.add(src, arcname=m.src_rel)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    if not VAULT_ROOT.is_dir():
        print(f"vault not found: {VAULT_ROOT}", file=sys.stderr)
        return 2

    moves = build_moves()

    # Verify sources + classify collisions
    missing: list[Move] = []
    identical_dupes: list[tuple[Move, Path]] = []  # source will be deleted
    divergent: list[tuple[Move, Path]] = []  # skipped — needs manual merge
    valid: list[Move] = []  # true moves (no destination conflict)
    for m in moves:
        src = VAULT_ROOT / m.src_rel
        if not src.exists():
            missing.append(m)
            continue
        dest = m.dest_dir / src.name
        if dest.exists():
            try:
                same = _sha256(src) == _sha256(dest)
            except OSError:
                same = False
            if same:
                identical_dupes.append((m, dest))
            else:
                divergent.append((m, dest))
            continue
        valid.append(m)

    # Print plan
    print("=" * 72)
    print(f"VAULT CLEANUP — PHASE 4   ({'APPLY' if args.apply else 'DRY-RUN'})")
    print("=" * 72)
    print(f"Vault: {VAULT_ROOT}")
    print()
    print(f"Total moves planned:   {len(moves)}")
    print(f"  clean moves:         {len(valid)}")
    print(f"  identical dupes:     {len(identical_dupes)} (source will be DELETED)")
    print(f"  divergent conflicts: {len(divergent)} (SKIPPED — manual merge in Phase 2)")
    print(f"  missing sources:     {len(missing)}")
    print()

    by_cat: dict[str, list[Move]] = {}
    for m in valid:
        by_cat.setdefault(m.category, []).append(m)
    for cat in sorted(by_cat.keys()):
        group = by_cat[cat]
        dest = group[0].dest_dir.relative_to(VAULT_ROOT)
        print(f"[{cat}] → {dest}/  ({len(group)} files)")
        for m in group[:6]:
            print(f"   - {Path(m.src_rel).name}")
        if len(group) > 6:
            print(f"   … {len(group) - 6} more")
        print()

    if identical_dupes:
        print(f"[IDENTICAL DUPES] {len(identical_dupes)} — source will be deleted")
        for m, d in identical_dupes[:30]:
            print(f"   ✓ {Path(m.src_rel).name}  ==  {d.relative_to(VAULT_ROOT)}")
        print()

    if divergent:
        print(f"[DIVERGENT CONFLICTS] {len(divergent)} — skipped, manual merge needed")
        for m, d in divergent[:30]:
            print(f"   ✗ {Path(m.src_rel).name}  ≠  {d.relative_to(VAULT_ROOT)}")
        print()

    if missing:
        print(f"[MISSING SOURCES] {len(missing)}")
        for m in missing[:20]:
            print(f"   ! {m.src_rel}")
        print()

    if not args.apply:
        print("(dry-run) no files were modified. Re-run with --apply to execute.")
        return 0

    print("Creating backup archive …")
    backup_list = valid + [m for m, _ in identical_dupes]
    backup = make_backup(backup_list)
    print(f"  backup saved: {backup}")
    print()

    # Create destination dirs
    for d in {TERM_DIR, MEDIA_DIR, BOOK_DIR, PLACES_DIR}:
        d.mkdir(parents=True, exist_ok=True)

    moved = 0
    deleted_dupes = 0
    errors: list[str] = []
    for m in valid:
        src = VAULT_ROOT / m.src_rel
        dest = m.dest_dir / src.name
        try:
            shutil.move(str(src), str(dest))
            moved += 1
        except OSError as exc:
            errors.append(f"move {m.src_rel}: {exc}")

    for m, _ in identical_dupes:
        src = VAULT_ROOT / m.src_rel
        try:
            src.unlink()
            deleted_dupes += 1
        except OSError as exc:
            errors.append(f"delete dupe {m.src_rel}: {exc}")

    print(f"Moved {moved}/{len(valid)} files.")
    print(f"Deleted {deleted_dupes}/{len(identical_dupes)} identical dupes.")
    if divergent:
        print(f"Skipped {len(divergent)} divergent conflicts (need manual merge).")
    if errors:
        print()
        print(f"[ERRORS] {len(errors)}")
        for e in errors[:20]:
            print(f"   ! {e}")

    print()
    print("Phase 4 complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
